import json
import matplotlib.pyplot as plt

# Load evaluation report generated by evaluate.py
with open('evaluation_report/evaluation_report.json', 'r') as f:
    report = json.load(f)

# Extract per-class recall (accuracy within each class)
class_metrics = report.get('class_metrics', {})

# Filter out non-class keys (like accuracy / macro avg)
classes = []
recalls = []
for cls, metrics in class_metrics.items():
    if cls in ['accuracy', 'macro avg', 'weighted avg']:
        continue
    classes.append(cls)
    recalls.append(metrics.get('recall', 0.0))

# Make bar plot
plt.figure(figsize=(8, 5))
bars = plt.bar(classes, recalls, color=['blue', 'orange'][:len(classes)])
plt.ylim(0, 1.05)
plt.ylabel('Recall (Per-Class Accuracy)')
plt.title('Per-Class Recall (Accuracy)')
plt.grid(axis='y', linestyle='--', alpha=0.7)

for bar, r in zip(bars, recalls):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'{r:.3f}',
             ha='center', va='bottom', fontweight='bold')

plt.savefig('class_accuracy.png')
plt.show()
